# Generated by Django 5.2.6 on 2025-09-13 08:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Connection name', max_length=100)),
                ('provider', models.CharField(choices=[('apple', 'Apple Calendar (iCloud)'), ('google', 'Google Calendar'), ('outlook', 'Outlook Calendar')], max_length=20)),
                ('server_url', models.URLField(help_text='CalDAV server URL')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(help_text='App-specific password or token', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, help_text='External calendar event ID', max_length=255, null=True)),
                ('calendar_source', models.CharField(blank=True, help_text='Source calendar (apple, google, etc.)', max_length=50, null=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
